title: Ithaca DSA
email: ithacanydsa@gmail.com
description: >-
  The website of the Ithaca, NY Local of Democratic Socialists of America.
baseurl: ""
url: "https://ithacadsa.org"
twitter_username: ithacadsa
facebook_username: ithacadsa
instagram_username: ithacadsa

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "assets/img"
    values:
      images: true

assets:
   sources:
       -_assets/font

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
